import "./globals.css";
import { Inter } from "next/font/google";
import Container from "@/components/Container";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "지호의 블로그",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="kr">
      <body className={inter.className}>
        <Container>{children}</Container>
      </body>
    </html>
  );
}
